name: windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.6.x', '2.5.x' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Download test readline
      run: |
        download_test_readline.bat
    - name: Run test
      run: |
        rake ci-test
